spring:
  application:
    name: course-catalog-service
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5438/contacts  # for use with docker-compose.yml built image
#    url: jdbc:postgresql://localhost:5432/contacts  # for use locally built postgres database
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop #this recreates the db, not recommended for prod
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
message: Hello from default profile
---
spring.config.activate.on-profile: docker
server.port: 8080